### ISSUE TITLE
On peut pas push dans les branches (sauf Master)

### ISSUE THREAD

**Issue by SauAmaury** [shukakyu/Graphes#3]
J'ai ajouter une méthode isolerSommet qui semble marcher selon mes test et facilite le code et la compréhension.
J'ai vite fait essayer de faire le graphe des licornes.

Mais je peux pas encore vous montrer le code car je peux push que dans Master et j'ai pas envie de brailler tout le code de la branche Master si jamais ça marche pas.

**Comment by RaphaelPinto18** [comment]
Ok chef :p nice one mais pense à dormir heiin^^...

**Comment by SauAmaury** [comment]
@shukakyu Du coup tu peux autoriser le push dans les branches autre que Master please ? ^^'

**Comment by nyc4m** [comment]
Il n'y a pas de droits sur les branches, mais il faut juste indiquer que tu veux utiliset une branche :) tu travailles en ligne de commande ?

**Comment by SauAmaury** [comment]
![image](https://cloud.githubusercontent.com/assets/16886724/14770293/33beee00-0a6e-11e6-84c1-1b4390535e27.png)

Non je travaille pas en ligne de commande juste sur Netbeans

**Comment by nyc4m** [comment]
Arrête ça tout de suite et apprends la ligne de commande, ça évitera ce genre de problème ;)
